services:
  mysql:
    image: mysql:8.0
    container_name: mysql_super_ar
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - database_network

  redis:
    image: redis:8-alpine
    container_name: superar-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes

  api:
    build: ./backend
    # env_file: ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
      - redis

    networks:
      - app_network
      - database_network
  
  mqtt:
    build:
      context: ./mqtt-service

    restart: unless-stopped

    volumes:
      - ./mqtt-service:/app

    environment:
      API_URL: http://api:5000
      INTERNAL_API_TOKEN: ${INTERNAL_API_TOKEN}

      MQTT_BROKER_HOST: ${MQTT_BROKER_HOST}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT}
      MQTT_TOPIC_STATUS: ${MQTT_TOPIC_STATUS}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}

    depends_on:
      - api

    networks:
      - app_network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # ajuda bastante em Linux/WSL para o watcher
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - api
    networks:
      - app_network
volumes:
  mysql_data:
  redis_data:

networks:
  app_network:
    driver: bridge

  database_network:
    driver: bridge
    internal: true
