services:
  mysql:
    image: mysql:8.0
    container_name: mysql_super_ar
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
  api:
    build: ./backend
    # env_file: ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # ajuda bastante em Linux/WSL para o watcher
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - api
volumes:
  mysql_data:
